//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassRelationships.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDetail
    {
        public int CustId { get; set; }
        public string Name { get; set; }
        public string Nic_No { get; set; }
        public string Account_No { get; set; }
        public decimal Account_Bal_ { get; set; }
        public string Address { get; set; }
    }
}
